docs: Update instructions to run the validator
MobilityData/gtfs-validator pull request #1115
Opened 2022-03-16 16:49 UTC by isabelle-dr

**Summary:**
After receiving feedback from users on our instructions to run the validator via the command line, we identified the following pain points:
- the user didn't know that the file downloaded from `test-pack-doc` needed to be unzipped to access the jar file
- no mention that the user needs to navigate to the folder where the jar file is before running the command line (we can't use a path for the -jar argument)
- it's not clear what the country code argument is used for
- the fact that the command-line examples in USAGE.md aren't using the same parameter names as in README.md is confusing (the example in USAGE.md is using long names for parameters, and the example in README.md is using short names)

This PR solves these problems by:
- Updating the instructions in the README.md
- Updating USAGE.md to have more homogeneity between the two

This PR also includes:
- an update to the description of InvalidPhoneNumberNotice in RULES.md to specify that this notice depends on the country code
- a fix in USAGE.md to switch Java 8 to Java 11
- added examples and fixed the requirements for the command line parameters in USAGE.md

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] ~~Run the unit tests with `gradle test` to make sure you didn't break anything~~
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2022-03-23 23:17 UTC, maximearmstrong requested changes
Great update! A few comments in-line before approval :)

2022-03-23 23:17 UTC, maximearmstrong commented on docs/USAGE.md
> +| `-t`       | `--threads`                   | Optional               | Number of java threads to use.
```suggestion
| `-t`       | `--threads`                   | Optional               | Number of threads to be used by Java to run the validator.                                                                                                                                                                                                                                                           |
```

2022-03-23 23:17 UTC, maximearmstrong commented on docs/USAGE.md
> +| `-o`       | `--output`                    | Required               | Path where the validation report will be stored (e.g., `output`)
```suggestion
| `-o`       | `--output`                    | Required               | Path to where the validation report will be stored (e.g., `output`)                                                                                                                                                                                                                         |
```

2022-03-27 23:42 UTC, isabelle-dr commented
Thanks for the feedback, I updated the instructions to replace [ with {. 
PTAL @maximearmstrong

2022-04-20 20:22 UTC, maximearmstrong approved these changes
LGTM! Thanks @isabelle-dr :)

2022-04-20 20:22 UTC, merged