Refactor cli.Main into ValidationRunner for easier reuse.
MobilityData/gtfs-validator pull request #1145
Opened 2022-05-12 07:26 UTC by bdferris-v2

Per discussion in issue #1135 and https://bit.ly/gtfs-validator-packaged-exe#heading=h.fcbgc2jy8dh, we'd like to refactor code in cli.Main into a new class that's easier to call from other contexts, including the new GUI-based app.

This PR moves the bulk of the code in `gtfsvalidator.cli.Main` into a new `gtfsvalidator.runner.ValidationRunner` class that does the work for setting up and running validation.  The configuration for the run is passed via a new ValidationRunnerConfig class.

Both `gtfsvalidator.cli.Main` and `gtfsvalidator.app.gui.Main` have been refactored to use this new validation runner.  The gui app now uses the return code from the runner to potentially open system_errors.json when appropriate.

Command-line argument parsing is left in the existing `Arguments` class, which I've refactored to produce a config object as its primary output.  I'll also merged in the logic from `gtfsvalidator/cli/CliParametersAnalyzer.java`, since it made the interface for `Arguments` simpler and I think conceptually it seems reasonable to include it there.

2022-05-12 07:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gtfs-validator?pullRequest=1145) it.</sub>

2022-05-12 22:04 UTC, maximearmstrong requested changes
2 small things before approval. Otherwise, this is great. Thank you @bdferris-v2

2022-05-12 22:21 UTC, bdferris-v2 commented on app/gui/src/main/java/org/mobilitydata/gtfsvalidator/app/gui/Main.java
> +import javax.swing.*;
Just a quirk of Intellij's import logic.  I inlined it to JOptionPane.

2022-05-12 22:21 UTC, bdferris-v2 commented on main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java
> +  private static Gson createGson(boolean pretty) {
Technically still used below in `exportNoticeSchema()`.  I just inlined the method since it's simple and not reused anywhere in the file.

2022-05-13 06:15 UTC, bdferris-v2 commented
I addressed the suggested changes and test are now fully passing.  I believe this is ready for a final review.

2022-05-13 14:49 UTC, maximearmstrong commented
We had to reconfigure the CLA wizard, so if possible, could you re-sign it with your second account? We will be ready to merge right after.

2022-05-13 14:57 UTC, bdferris-v2 commented
I just resigned.  Let me know if you need anything else?

2022-05-13 16:00 UTC, maximearmstrong approved these changes
All good! Thank you @bdferris-v2

2022-05-13 16:00 UTC, merged

2022-05-13 16:02 UTC, barbeau approved these changes
LGTM, thanks @bdferris-v2!

2022-05-13 16:02 UTC, barbeau commented on main/src/main/java/org/mobilitydata/gtfsvalidator/runner/ValidationRunner.java
> +    if (!feedContainer.isParsedSuccessfully()) {
The `Status` codes put us in a good position to handle https://github.com/MobilityData/gtfs-validator/issues/1096 as well via something like `Status.PARSING_FAILED`, which is to surface the condition where parsing failed and many validators weren't invoked. That can be in a future PR.