feat: add recommended field notice
MobilityData/gtfs-validator pull request #1157
Opened 2022-05-18 15:36 UTC by KClough

**Summary:**

Related #885

**Expected behavior:** 

Adds the recommended field notice.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
~- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2022-06-28 18:54 UTC, maximearmstrong requested changes
Thanks @KClough! A few things before approval.

2022-06-28 18:54 UTC, maximearmstrong commented on core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java
> +              fileName, row.getRowNumber(), header.getColumnName(columnIndex)));
It seems to be the duplication of the 4 previous lines.
```suggestion
```

2022-06-29 20:46 UTC, KClough commented on core/src/main/java/org/mobilitydata/gtfsvalidator/parsing/RowParser.java
> +    } else if (level == FieldLevelEnum.RECOMMENDED && s == null) {
Good call. I've added some unit tests for both Recommended and Required. Let me know if you'd like me to cover any additional cases.

2022-06-29 21:27 UTC, maximearmstrong approved these changes
LGTM, thank you @KClough!

2022-06-29 21:27 UTC, merged