docs: Fix broken links in RULES.md
MobilityData/gtfs-validator pull request #1295
Opened 2022-11-18 01:29 UTC by dsaldonid

**Summary:**
In response to issue #1294 .
Fixed broken stop_times.txt specs link in RULES.md and Best Practice Github repo link in  missing_timepoint_column.

**Expected behavior:** 

Clicking on the stop_time.txt specs and Best Pratice Github repo link should point to the proper place now!

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x ] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2022-11-18 01:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1295) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1295) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gtfs-validator?pullRequest=1295) it.</sub>

2022-11-22 12:56 UTC, isabelle-dr requested changes
Thank you for this contribution @dsaldonid! You're awesome 🙌
Could you change the Best Practices link to https://gtfs.org/schedule/best-practices/#stop_timestxt?

Would you agree to also update the following two links? We are trying to have all our doc referencing gtfs.org when possible 😊
- feed_info.txt links in `missing_recommended` file and `missing_recommended_field` to be replaced with https://gtfs.org/schedule/best-practices/#feed_infotxt

Thanks again 🙏

2022-11-22 16:53 UTC, dsaldonid commented
@isabelle-dr Yeah, no problem!

2022-12-05 17:41 UTC, isabelle-dr commented
Hey @dsaldonid, FYI we are going to publish a release before the end of the year with documentation updates, it would be great to have this contribution merged by then! 
Are planning to make the modifications soon?

2023-01-30 20:31 UTC, isabelle-dr commented
Closing, the fixes have been made in #1307

2023-01-30 20:31 UTC, closed without merging