fix: Add notice for missing stop name for specific location types
MobilityData/gtfs-validator pull request #1316
Opened 2023-01-19 15:33 UTC by briandonahue

**Summary:**

Adds validation for requires stop name for STOP, STATION, ENTRANCE location types. Addresses #1078 

**Expected behavior:** 

Should generate an Error notice if stop name is missing for the above location types.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [] Include screenshot(s) showing how this pull request works and fixes the issue(s) (N/A)

2023-01-19 15:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1316) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gtfs-validator?pullRequest=1316) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gtfs-validator?pullRequest=1316) it.</sub>

2023-02-10 05:47 UTC, bdferris-v2 commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java
> +    private final String routeDesc;
routeDesc => stopDesc

2023-02-10 05:49 UTC, bdferris-v2 commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StopNameValidator.java
> +    private final String routeDesc;
I'm not sure it's worth including stopDesc here.  It's not really relevant to the name.

2023-02-10 05:51 UTC, bdferris-v2 approved these changes
Modulo the one comment, this LGTM.

2023-02-10 17:03 UTC, isabelle-dr requested changes
The new rule LGTM, we just need the RULES.md update :)

More a general thought than something specific to this PR: I wonder if we want to formalize our preferred approach between:
- generating a custom notice for the conditionally required fields
- re-using `MissingRequiredField`

2023-02-10 19:49 UTC, briandonahue commented
> The new rule LGTM, we just need the RULES.md update :)

@isabelle-dr updated!

2023-02-11 01:06 UTC, bdferris-v2 commented
@isabelle-dr apologies I missed the RULES.md update on this.  I've taken a stab at adding a unit-test to catch this sort of thing in #1331.

2023-02-13 19:03 UTC, isabelle-dr reviewed
Just two propositions for the definitions, thanks for updating this so quickly @briandonahue!
Why are there also modifications to the java files in this PR?

2023-02-13 19:03 UTC, isabelle-dr commented on RULES.md
> +| [`missing_stop_name`](#missing_stop_name)                                                                                         | Missing required `stop_name` for stop with location type of `0`,
```suggestion
| [`missing_stop_name`](#missing_stop_name) | `stops.stop_name` is required for `location_type` equal to `0`, `1`, or `2`. |
```

2023-02-13 19:03 UTC, isabelle-dr commented on RULES.md
> +Missing required `stop_name` for stop with location type of `0`, `1`, or `2`.
```suggestion
`stops.stop_name` is required for locations that are stops (`location_type=0`), stations (`location_type=1`) or entrances/exits (`location_type=2`).
```

2023-02-13 19:12 UTC, briandonahue commented
> Why are there also modifications to the java files in this PR?

@isabelle-dr this PR contains the updated validation and the RULES.md update to go along with it.  Should they be separate?

2023-02-14 16:45 UTC, isabelle-dr approved these changes
Sorry, I got mixed up with #1330 🙈. 
This is perfect! LGTM

2023-02-14 16:46 UTC, isabelle-dr commented
Can you update this branch with the latest master?

2023-02-22 22:52 UTC, merged