Touch for #379
MobilityData/gtfs-validator pull request #462
Opened 2020-10-27 17:47 UTC by fabrice-v

Please create the PR and a member of the Mobility Data team will take it from here - thanks!

- [ ] This PR only touches `end_to_end.ym` in `.github/workflows
- [ ] `-abort_on_error to `false`
- [ ] Null Pointer Exception --> add bug and NPE tag
- [ ] Attach the dataset and report from the workflow run to this PR

***
***

**Summary:**

Summarize the changes in the pull request including how it relates to any issues (include the #number, or link them).

**Expected behavior:** 

Explain and/or show screenshots for how you expect the pull request to work in your testing (in case other devices exhibit different behavior).

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2020-10-27 23:58 UTC, fabrice-v commented
[bart.zip](https://github.com/MobilityData/gtfs-validator/files/5448713/bart.zip)

[validation_report_all.zip](https://github.com/MobilityData/gtfs-validator/files/5448717/validation_report_all.zip)

2020-10-28 13:22 UTC, lionel-nj requested changes
The link in job was not the good one, we should check with the one I suggest. However, the linked issue seems related to https://github.com/MobilityData/gtfs-validator/pull/433, where the same bug was fixed.

2020-10-28 13:22 UTC, lionel-nj commented on .github/workflows/end_to_end.yml
> +        run: java -jar application/cli-app/build/libs/*.jar -u http://transitfeeds.com/p/siskiyou-transit-and-general-express/492/latest/download -i bart.zip -e input -o output
```suggestion
        run: java -jar application/cli-app/build/libs/*.jar -u http://www.bart.gov/dev/schedules/google_transit.zip -i bart.zip -e input -o output
```

2020-10-29 10:50 UTC, fabrice-v commented
> The link in job was not the good one, we should check with the one I suggest. However, the linked issue seems related to #433, where the same bug was fixed.

I know. There is something weird. You should be in good shape to investigate and debug.
Thks,

2020-11-02 17:01 UTC, lionel-nj commented
>  compute Path in a separate use case (mmmm that actually was for json report path generation (name of the json report file), so not sure it applies here. I'll let you decide and let me know what you implemented/issues created/... you ended up putting or not in this PR in a convenient way for you, @lionel-nj

I will open an issue regarding this, and implement in a separate PR if that is okay with you

2020-11-02 21:13 UTC, lionel-nj commented
As https://github.com/MobilityData/gtfs-validator/runs/1344351102?check_suite_focus=true demonstrates:the error is no longer raised.

2020-11-02 22:09 UTC, fabrice-v commented on .github/workflows/end_to_end.yml
> +    branches: [ master,  bay-area-rapid-transit] #<-- replace transport-agency-name by the name of the agency/publisher
```suggestion
    branches: [ master,  transport-agency-name] #<-- replace transport-agency-name by the name of the agency/publisher
```

2020-11-02 22:12 UTC, fabrice-v reviewed
Lgtm (can't approve as author). Thks lionel, I'm merging now

2020-11-02 22:14 UTC, lionel-nj approved these changes
LGTM

2020-11-02 22:22 UTC, merged