implement #392
MobilityData/gtfs-validator pull request #477
Opened 2020-11-04 19:35 UTC by lionel-nj

closes #392 
**Summary:**

This PR provides support to improve notice descriptions

**Expected behavior:** 

To be updated 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Run the unit tests with `gradle test` to make sure you didn't break anything
- [ ] Format the title like "Fix #<issue_number> - <short description of fix and changes>" (for example - "Fix #1111 - Check for null value before using field")
- [ ] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2020-11-05 16:51 UTC, lionel-nj commented
@maximearmstrong  note that notice memory consumption tests fail on CircleCI (for 1000 and 10000 notices) but they pass locally and in Github Actions.

2020-11-09 14:25 UTC, lionel-nj commented
I actually remember that we did not want these tests to be hardware dependant, but the experience shows different behavior in Circle CI and GitHub actions. I'll add this subject to the next technical meeting agenda: do you think tha we should run test with different thresholds depending on whether CI is GitHub Actions or Circle CI? @maximearmstrong  @fabrice-v

2020-11-09 17:54 UTC, maximearmstrong commented
@lionel-nj I don't think we should run different tests (thresholds) depending on which CI runs the code. This being said, what makes tests fail on Circle CI? Is it the `SAFETY_BUFFER_FACTOR` that is not high enough or is it failing before assertion? If the problem comes from the safety threshold, I suggest increasing it. If not, we should investigate what fails. If we consider keeping both GitHub CI and Circle CI in the future, one option would be to disable that test on Circle CI as it could be linked to its memory consumption. CC @fabrice-v

2020-11-09 19:35 UTC, maximearmstrong requested changes
Minor request changes. Most of your `String.format()` displays one variable per line, which makes it very easy to read the code. In some cases, there are many variables per line, making it harder to read. Other than that, looks good!

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/FastTravelBetweenStopsNotice.java
> +                        tripId, stopSequenceList, speedKmh),
Nothing really, but in any other file, you put one variable per line (for clarity I assume). Maybe just do the same here to maintain the same scheme.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/DuplicatedEntityNotice.java
> +                        compositeKeyFirstPart, compositeKeyFirstValue,
One variable per line would be better for readability.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/FeedInfoExpiresInLessThan7DaysNotice.java
> +                        compositeKeyFirstPart, compositeKeyFirstValue,
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/MissingHeaderNotice.java
> +                String.format("GTFS file `%s` is missing required field: `%s`.", filename, missingHeaderName),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/MissingRequiredFileNotice.java
> +                String.format("GTFS file `%s` is required.", filename),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/ExtraFileFoundNotice.java
> +                String.format("Extra file `%s` found in archive", filename),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/InputZipContainsFolderNotice.java
> +                String.format("File: `%s` contains folder named: `%s`", filename, folderName),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/MissingRouteLongNameNotice.java
> +                        entityId, filename),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/MissingRouteShortNameNotice.java
> +                        entityId, filename),
Same as above.

2020-11-09 19:35 UTC, maximearmstrong commented on domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/warning/RouteLongNameContainsShortNameNotice.java
> +                                " and should not contain the `route_short_name`.", filename),
Same as above.

2020-11-09 22:09 UTC, lionel-nj commented
> @lionel-nj I don't think we should run different tests (thresholds) depending on which CI runs the code. This being said, what makes tests fail on Circle CI? Is it the SAFETY_BUFFER_FACTOR that is not high enough or is it failing before assertion? If the problem comes from the safety threshold, I suggest increasing it. If not, we should investigate what fails. If we consider keeping both GitHub CI and Circle CI in the future, one option would be to disable that test on Circle CI as it could be linked to its memory consumption. CC @fabrice-v

Actually these failures are totally random so I could not determine the source of the the failure. As you can see:
- 1 job that fails: https://app.circleci.com/pipelines/github/MobilityData/gtfs-validator/393/workflows/8ecd5f22-3a14-427f-8977-4c5e92959a66
- successful re-run of the same job: https://app.circleci.com/pipelines/github/MobilityData/gtfs-validator/393/workflows/0c684c9b-cab2-43cc-b451-b3dc976ea801

It is also to note that even bumping the threshold did not stop this job from failing.

2020-11-10 14:01 UTC, lionel-nj commented
To answer your question, from what I witnessed the tests fail at the assertion steps, which leads me to think that the thresholds was not sufficient. However, the same tests pass locally and on GitHub and I doubt that we should continue to extend these thresholds, otherwise we would not be testing thoroughly

2020-12-03 23:51 UTC, closed without merging