docs: fix, build and persist javadocs
MobilityData/gtfs-validator pull request #718
Opened 2021-02-03 20:13 UTC by lionel-nj

**Summary:**

This PR fixes, and adds the process to build and persiste javadoc as artefact.

**Expected behavior:** 

Javadoc should be generated and persisted in the artefact list.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: -new feature short description-" (PR title must follow the [conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2021-02-03 21:40 UTC, maximearmstrong requested changes

2021-02-03 21:40 UTC, maximearmstrong commented on core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Required.java
> + *       {@literal @}String agencyName();
Is "Required" removed willingly?

2021-02-03 21:46 UTC, lionel-nj commented on core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/Required.java
> + *       {@literal @}String agencyName();
Not at all, thanks for flagging that!

2021-02-08 20:10 UTC, maximearmstrong approved these changes
LGTM

2021-02-10 21:49 UTC, barbeau approved these changes
LGTM, although prior to merging I'd like to get @aababilov's feedback as mentioned in-line, given he wrote this originally.

2021-02-10 21:49 UTC, barbeau commented on core/src/main/java/org/mobilitydata/gtfsvalidator/annotation/PrimaryKey.java
> + *   {@literal @}Generated
@aababilov Do any of these Javadoc changes cause issues for you at Google? 

As @lionel-nj states in https://github.com/MobilityData/gtfs-validator/pull/718#issue-567114622 these are required to get the Javadocs to generate and render correctly. @lionel-nj looked at the Google Java Style Guide and it doesn't seem to cover this type of formatting, and as https://reflectoring.io/howto-format-code-snippets-in-javadoc/ indicates there are different ways to solve this problem. It looks like the changes @lionel-nj made here resolve the issue and can be merged, providing they aren't problematic for you.

2021-02-16 22:38 UTC, merged