feat: check conditional requirements on translations fields
MobilityData/gtfs-validator pull request #795
Opened 2021-03-09 18:27 UTC by lionel-nj

**Summary:**

This PR provides support to verify conditional requirements on GTFS file `translations.txt`.

**New notices:** 
- TranslationFieldValueDefinedNotice
- TranslationFieldValueNotDefinedNotice
- TranslationRecordIdDefinedNotice
- TranslationRecordIdNotDefinedNotice
- TranslationRecordSubIdDefinedNotice
- TranslationRecordSubIdNotDefinedNotice

**Expected behavior:** 

A notice should be generated and added to the `NoticeContainer` if: 
- table_name is feed_info and:
  - record_id is defined
  - record_sub_id is defined
  - field_value is defined
 - table_name is stop_times, record_id is defined and record_sub_id is not defined
 - field_value is defined and:
   - record_id is defined
   - record_sub_id is defined
  - field_value is empty
    - record_id is not defined
 - field_value and record_sub_id are defined
 - field_value and record_id are defined 
 - record_id is empty and field value is not defined
 
http://gtfs.org/reference/static#translationstxt

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-03-09 18:46 UTC, lionel-nj commented
@barbeau Should `GtfsTranslation.tableName()` return and enum value instead of String values? This field is defined by the spec as an enum and the speficiation says:

> Allowed values are: agency, stops, routes, trips, stop_times, pathways, levels, feed_info and attributions (do not include the .txt file extension)

2021-03-09 23:03 UTC, maximearmstrong requested changes

2021-03-09 23:13 UTC, barbeau reviewed
@lionel-nj Here's what I have so far, although I haven't looked at the implementations yet.

2021-03-10 02:14 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/TranslationConditionalRequirementsValidator.java
> +      if (translation
Unfortunately, that approach does not scale well. GTFS spec defines a lot of files and users may add their extensions with new fields and fields.

We need changes to the validator core. The annotation processor should provide information about the schema and validator classes may receive that as a part of validation context.

I can make the necessary changes to the core when I come back after 15 March.

2021-03-17 23:29 UTC, lionel-nj commented
Closing for now, will resume implementation as part of v2.1.

2021-03-17 23:29 UTC, closed without merging