refactor: make StoptimeOutOfOrderTimesValidator extend SingleFileValidator
MobilityData/gtfs-validator pull request #809
Opened 2021-03-15 20:53 UTC by lionel-nj

**Summary:**

This PR provides changes to make extract the rule that checks the order of times in `stop_times.txt` as a new rule that extends `SingleFileValidator`  class. 

**Expected behavior:** 

Unit tests have been adapted to this refactor, but no logic has changed. Therefore the same logic for existing tests should pass. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2021-03-15 23:56 UTC, aababilov commented
Make sense, Lionel!

What came to my mind: that may be a basic validation in Core. I will add a new annotation to validate that times and dates are in order.

2021-03-15 23:56 UTC, aababilov requested changes

2021-03-15 23:56 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/StoptimeOutOfOrderTimesValidator.java
> +      if (stopTime.departureTime().isBefore(stopTime.arrivalTime())) {
Please collapse that to a single "if" here.

2021-03-15 23:56 UTC, aababilov commented on main/src/test/java/org/mobilitydata/gtfsvalidator/validator/StoptimeOutOfOrderTimesValidatorTest.java
> +  }
Please make it more concise like here:

```
private static List<ValidationNotice> generateNotices(GtfsAttribution attribution) {
    NoticeContainer noticeContainer = new NoticeContainer();
    AttributionWithoutRoleValidator validator = new AttributionWithoutRoleValidator();
    validator.validate(attribution, noticeContainer);
    return noticeContainer.getValidationNotices();
  }

  @Test
  public void attributionWithoutRoleShouldGenerateNotice() {
    assertThat(
            generateNotices(
                new GtfsAttribution.Builder()
                    .setCsvRowNumber(2)
                    .setAttributionId("attr-1")
                    .build()))
        .containsExactly(new AttributionWithoutRoleNotice(2, "attr-1"));
  }
```

2021-03-16 10:47 UTC, aababilov commented
Here is an annotation-based solution: https://github.com/MobilityData/gtfs-validator/pull/813

2021-03-17 15:46 UTC, lionel-nj commented
Closing as implemented in #813.

2021-03-17 15:46 UTC, closed without merging