refactor: remove mocks from CliParametersAnalyzerTest
MobilityData/gtfs-validator pull request #854
Opened 2021-04-15 17:05 UTC by lionel-nj

closes #591 

**Summary:**

This PR provides suppport to:
- remove mocks from `CliParametersAnalyzerTest` 
- fix randonly failing tests on CI

**Expected behavior:** 

Tests should pass on CI.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `gradle test` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-04-26 06:21 UTC, aababilov requested changes

2021-04-26 06:21 UTC, aababilov commented on main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java
> +  public void isValid_false() {
Please split that into separate tests for each scenario.

Remember that a failed assertThat interrupts your test. In your code, you test multiple scenarios, so the first failed scenario prevents the following ones and test output is incomplete.

2021-04-26 06:21 UTC, aababilov commented on main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java
> +  public void isValid_false() {
Please avoid code duplication. Create a helper static method that would accept your String [] argv, validate them and return the result of isValid().

2021-04-26 13:39 UTC, lionel-nj commented
Thanks for review @aababilov, PTAL.

2021-04-26 19:18 UTC, aababilov requested changes

2021-04-26 19:19 UTC, aababilov requested changes
Please also remove mockito from main/build.gradle.

2021-05-03 18:51 UTC, lionel-nj commented on main/src/test/java/org/mobilitydata/gtfsvalidator/cli/CliParametersAnalyzerTest.java
> +  public void noUrlNoInput_isNotValid() {
Thanks for the heads-up @aababilov!

2021-05-03 18:53 UTC, lionel-nj commented
Thanks for review @aababilov! I modified the tests following your suggestions. I only kept test using long names since as you mentioned previously: using the short names for the same scenarios is not relevant - given that `ArgumentsTest` already checks arguments initialization whether we're using short or long names.

2021-05-04 01:27 UTC, aababilov approved these changes
Thanks!

2021-05-04 13:56 UTC, merged