docs: update documentation to match v2.0.0 development
MobilityData/gtfs-validator pull request #915
Opened 2021-06-22 13:58 UTC by lionel-nj

relates to https://github.com/MobilityData/gtfs-validator/issues/904

**Summary:**

This PR updates the documentation of v2.0.0 release to match the development of 2.0.0 version of the validator.

**Expected behavior:** 

No code change.

Please make sure these boxes are checked before submitting your pull request - thanks!

- ~[ ] Run the unit tests with `gradle test` to make sure you didn't break anything~
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- ~[ ] Include screenshot(s) showing how this pull request works and fixes the issue(s)~

2021-06-22 14:59 UTC, barbeau commented
This shouldn't be merged to master though, right? It should stay in its own branch to be tagged as a replacement for v2 release? This branch should also branch off of the v2 release tag if the intent is to fix the v2 release docs.

2021-06-22 15:29 UTC, lionel-nj commented
> This shouldn't be merged to master though, right? 

No it should not. 

>  It should stay in its own branch to be tagged as a replacement for v2 release? This branch should also branch off of the v2 release tag if the intent is to fix the v2 release docs.

Yes, it would come as a replacement for the v2 release

2021-08-25 13:06 UTC, isabelle-dr requested changes
@lionel-nj 
I added comments on what needs to be changed:
1- the `output` parameter that needs to be changed for `output_base`
2- the feed_name can't have capital letters, that is why Omar couldn't run this version of the validator

Can we also update the USAGE.md file with `output_base`?
Thanks!

2021-08-25 14:21 UTC, isabelle-dr commented on README.md
> +1. Download [gtfs-validator-v2.0.0_cli.jar](https://github.com/MobilityData/gtfs-validator/releases/download/v2.0.0/gtfs-validator-v2.0.0_cli.jar)
Add "Prepare your input directory. It has to be a compressed .zip folder containing all the GTFS feed text files. 
To compress a folder correctly, select all text files and select "Compress". Do not compress a folder from the folder icon."

2021-08-25 16:40 UTC, lionel-nj commented
Closing as solved.

2021-08-25 16:40 UTC, closed without merging