feat: Validate that pathway endpoints have correct types
MobilityData/gtfs-validator pull request #961
Opened 2021-08-16 11:31 UTC by aababilov

* a pathway may not lead to a station (location_type=1);
* if a platform has boarding areas, the pathway must be connected to
  its boarding areas instead of the platform itself.

2021-08-18 13:18 UTC, lionel-nj requested changes
Thanks @aababilov for your contribution - one comment in-line regarding the naming of `PathwayWrongEndpointTypeNotice`.

2021-08-18 13:18 UTC, lionel-nj commented on RULES.md
> +A pathway has an endpoint that is a platform which has boarding areas. A platform that has boarding
Here, @isabelle-dr @MobilityData/transit-specs do you think that it's worth updating the specification to clarify this rule (make it more explicit)?

2021-08-18 18:37 UTC, maximearmstrong approved these changes
+1 to @lionel-nj comment [here](https://github.com/MobilityData/gtfs-validator/pull/961#discussion_r691211750), but LGTM otherwise!

2021-08-23 06:36 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java
> +  static class PathwayWrongEndpointTypeNotice extends ValidationNotice {
This name was chosen on purpose. There is a proposal to add "clusters" as a new location type. Pathways may not be connected to clusters, so this notice name is suitable for both stations and clusters.

2021-08-23 06:40 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayEndpointTypeValidator.java
> +  static class PathwayWrongEndpointTypeNotice extends ValidationNotice {
But I see your point and let's call it `PathwayToWrongLocationTypeNotice`.

2021-08-23 06:42 UTC, merged