feat: Validate that locations are reachable if a station has pathways
MobilityData/gtfs-validator pull request #997
Opened 2021-09-01 14:49 UTC by aababilov

Fix issue 974, issue 975

Validate that if a station has pathways, then each location is
reachable in both directions: there is a way to get to that location
from some entrance and a way to get from that location to some
entrance.

Notices are reported for platforms, boarding areas and generic nodes
but not for entrances or stations.

Notices are not reported for platforms that have boarding areas since
such platforms may not have incident pathways. Instead, notices are
reported for the boarding areas.

2021-09-01 15:13 UTC, lionel-nj commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +   * entrances (opposite to the direction of pathways).
```suggestion
   * exits (opposite to the direction of pathways).
```

2021-09-01 19:42 UTC, lionel-nj requested changes
Thanks @aababilov for this contribution! You will fnd a few comments and questions in line. Also could you update `NOTICES.md` we are planning on possibly removing it but waiting for that it is good to keep it up to date.

2021-09-01 21:00 UTC, isabelle-dr reviewed
Amazing contribution! Thank you so much Alexei 🙏

Agreed with @lionel-nj on:
- Update NOTICES.md because it helps users understand the validation report :) We will officially remove it when the users will be able to see this information somewhere else
- Set the severity as an error to be compliant with the specification:

> Each platform (location_type=0 or empty) or boarding area (location_type=4) must be connected to at least one entrance/exit

2021-09-02 12:24 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +   * entrances (opposite to the direction of pathways).
Done.

2021-09-02 12:25 UTC, aababilov commented on main/src/test/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidatorTest.java
> +    long row = fromStopRow * 1000 + toStopRow;
We have fromStopRow and toStopRow, so let's have pathwayRow for consistency.

2021-09-02 12:31 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +  enum Traversal {
Let's even call it SearchDirection.

2021-09-02 12:32 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +  enum Traversal {
Done.

2021-09-02 12:34 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +   * Traverses pathway graph using BFS either from entrances (in the direction of pathways) or to
BFS is one of the simplest graph algorithms and being familiar with it is a part of an engineering culture. If a non-engineer reads the code, then explanation of BFS would not help much. Finally, there is Google for it :)

2021-09-02 12:35 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +    final Set<String> withEntrances = traversePathways(FROM_ENTRANCES);
I would interpret entryNodes as "generic nodes used for entry". Let's call it "locationsHavingEntrances".

2021-09-02 12:36 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +    final Set<String> withExits = traversePathways(TO_EXITS);
locationsHavingExits

2021-09-02 12:43 UTC, aababilov commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +      super(SeverityLevel.WARNING);
How did you get those numbers? My search in feeds at Google gives 30 violators of that rule out of 4'000 feeds, i.e. 1 of 133 feeds breaks that rule. Such feeds include top priority cities, so I highly recommend to keep treating them as valid. Losing those feeds would have a strong negative user impact.

I do the following trick to mitigate the problem of inaccessible platforms. When a platform is inaccessible, my algorithm treats it as street-accessible. So Google Maps just give the platform number without specifying walking instructions within the station.

2021-09-02 13:10 UTC, aababilov commented
I am very glad that you like my code and I am happy to merge it. Thanks for review!

2021-09-02 13:11 UTC, merged

2021-09-02 16:31 UTC, isabelle-dr commented on main/src/main/java/org/mobilitydata/gtfsvalidator/validator/PathwayReachableLocationValidator.java
> +      super(SeverityLevel.WARNING);
That trick about inaccessible platforms! 🔥

To clarify what Lionel wrote: In the extreme majority of cases, having an unreachable location in a station is _unintentional_, although it is present in some top priority cities datasets.

The vision for this validator at MobilityData is: 
1- Providing a canonical set of rules & their associated severity level to help users create spec-compliant datasets. This set of rules is as strict as the specification, and it supports one of our mission: support the creation of high-quality GTFS datasets. This is why we're [solving discrepancies ](https://github.com/MobilityData/gtfs-validator/pull/970)for the V3.0.0 release.
2- Allowing custom validation sets where a consumer can define what is making a dataset invalid for their app. They will be able to modify severity levels and also have additional rules. (this is the next feature we are planning on working on)

This means that a dataset triggering this notice will be treated as invalid with regards to the specification, and valid with regards to Google Maps.

What are your thoughts on this vision @aababilov?